[wip] Support Ruby 3.5 without warnings
$ bundle exec rake compile
Source locally installed gems is ignoring #<Bundler::StubSpecification name=io-console version=0.8.1 platform=ruby> because it is missing extensions
/home/yahonda/src/github.com/bcrypt-ruby/bcrypt-ruby/Rakefile:6: warning: rdoc/task is found in rdoc, which is not part of the default gems since Ruby 3.5.0.
You can add rdoc to your Gemfile or gemspec to fix this error.
rake aborted!
LoadError: cannot load such file -- rdoc/task (LoadError)
/home/yahonda/src/github.com/bcrypt-ruby/bcrypt-ruby/Rakefile:6:in '<top (required)>'
/home/yahonda/.local/share/mise/installs/ruby/trunk/bin/bundle:25:in '<main>'
(See full trace by running task with --trace)
yahonda@myubuntu:~/src/github.com/bcrypt-ruby/bcrypt-ruby$

yahonda@myubuntu:~/src/github.com/bcrypt-ruby/bcrypt-ruby$ bundle exec rake compile
Source locally installed gems is ignoring #<Bundler::StubSpecification name=io-console version=0.8.1 platform=ruby> because it is missing extensions
/home/yahonda/src/github.com/bcrypt-ruby/bcrypt-ruby/Rakefile:7: warning: benchmark used to be loaded from the standard library, but is not part of the default gems since Ruby 3.5.0.
You can add benchmark to your Gemfile or gemspec to fix this error.
rake aborted!
LoadError: cannot load such file -- benchmark (LoadError)
/home/yahonda/src/github.com/bcrypt-ruby/bcrypt-ruby/Rakefile:7:in '<top (required)>'
/home/yahonda/.local/share/mise/installs/ruby/trunk/bin/bundle:25:in '<main>'
(See full trace by running task with --trace)
yahonda@myubuntu:~/src/github.com/bcrypt-ruby/bcrypt-ruby$

$ bundle exec rake compile
Source locally installed gems is ignoring #<Bundler::StubSpecification name=io-console version=0.8.1 platform=ruby> because it is missing extensions
/usr/bin/gmake install sitearchdir=../../../../lib sitelibdir=../../../../lib target_prefix=
/usr/bin/install -c -m 0755 bcrypt_ext.so ../../../../lib
cp tmp/x86_64-linux/bcrypt_ext/3.5.0/bcrypt_ext.so tmp/x86_64-linux/stage/lib/bcrypt_ext.so
yahonda@myubuntu:~/src/github.com/bcrypt-ruby/bcrypt-ruby$ bundle exec rake compile